language: java
jdk: oraclejdk8
services:
- docker
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
addons:
  sonarcloud:
    organization: rageshk-github
    token:
      secure: ba6d7d1ad9a369f9f59e4ef1ae06f59dfa24ea35
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export IMAGE_NAME=rageshkh/healthcheeck-img
- docker build $IMAGE_NAME .
- docker push $IMAGE_NAME
env:
  matrix:
  - secure: roRplPJ5Z/A+MoL1ok4w3ijpwe9bY3ZWqF7N2N0RvQE5fm5tYxTg4RUhFCikHZnbQVdU4+vG3tovE0z2AmblZdJRRigOSuvP5LVUz1W9QsIPW7KKpOkXIhjKX0gswra8VpMyKgfm5Mt9er+1wXftTgVMv8bgB2Jbo5ZnRUUBNBjWdlbfQyIsCpQRAu1agrHhhk5r7VcxZMmYbrruwYE8QhkRZ9k6Ly40VCudpcWewaOh4mPqsgByU7ZkVwumv28Qs1dWBocGNyig6vpn+B1tOO+Wn0xytS9yfnpUxaqRpJgMVKHCelDh+gBs/P7Lz8soD95OihQtxcnllcpxaQGqAOwamA2tUJF7XzUknGvNnJOvnZdUV8KEFmRqV2n1mgQpbsKhM67DiuxU4lche/fYvqW033Cwg0JhiG/D+m/XaP0GLBJ/p9sehFVRUkVUDhjCN/iQh3GrbDG1drLgshEwZ0JTI/8Hat1QZVwHQancH0cGcspSVNrylvSdz62koBs+8iM1yR9HAwGz+BqWXA12gtrUTEoe/oGmO1rvGehzPC2PgyueciTt0/bzR0Mvmta4OKSVr2wlbD1Flzf1ThHJerGgl10uJovSkH9IRPRKiPEzT8YrI42+NiphqKpLyMaZ1l+rpYN7zySqact8ztw29nk22xbZ1N+INtEP1qN1yzk=
  - secure: O4A9QUR/SnXZcnQEPo2vx3tpLWp8RAyn2dOw14SFEpBwygNsWB8cKQFB+T5gfJz4eHYumTCIZNwhdPc2SzPzqey5NmekjrgCyeIVmdmpk+uvMhDlOJvWo1F6bZIe3c6WgSMGGRcF9GPN1nzpcN9JA1HwkOH2Wx6210MGiBqWo6Xzs18YzNy2egyC6aZTt6lvEsafxNWWf9wUZ79UbJC/MUrZXR6J8N4TK7DHM/mluFldhNihLTOHVi2MFEqWMiBYZ7FNeMYj9lt2mcvXZu2OrAeO52FtbQ/huzs9x5YX2ovF66auI1CX0kYkziEZfh5GKkjUyHI308o44wiskV3kWyNZCg9JwP3mlYtN047rfgPh9zjtU0Yd0CcmZ88ArNGB6xb2Uuq1WdjYKRI5xXzgqov+picXDHi+ih8s7eXdZA8ZI3FSjYtCu0H2YL01SzAsub1aWiTaBlYpdgJPjPFPHVK87iD8+oI3YC/7SbYHPL9hji+zhD6F6uAH8D63L8OzlfVD6pZQ1F+VqQ7nCz4e1Ultdj+SdCN+nTVw89MkWF16nI+XJRA1znkV6Mjx2+W3tqj5kXUJ9sSkkcnqKNah1+Et2lyjknt/iHX9B2d8/QTLagFbXxcDTpdIky5c/kxEbgjtHv9WeDH3JkBIHw0oujvPAap8ePwmsiVkwDEnqks=
