language: java
jdk: oraclejdk8
services:
- docker
before_install:
- chmod +x mvnw
env:
  global:
  - secure: 19oSoYoth5ke4W1jqfmSXrgBoLeRFy4Kw7Z5QzepPDIFQ4vZqQgZSeEjxMF+ksMWc+fFU8zJSmNQsV+nWV1f244Da0+WTKbE+p12SVNa8+HcHMuGoUWBqKBPTSu2CTyuSGQ91dh8pXkIovrVFc2y/SP24+uoIRMPW1OfkBiVY/Z0+WNLWbG5DxHrlHGlinQmKckRiDuTfb/RmdNe1mRsHTkTEZqx7ekZ3BW/gxwwZNaCvkiXFzaBNa6FAkhK44nUsTdP6+WP2MFNriPsQxTlpXpDhPfuGtPPYxrCP1EhQrpmsXlJ8nB64mGY1OtASmTZBbGAKIV5mdBMIbY0gRYhvU7UzCCRlVyfQt7R5wyQTI0ruyrDxEES4TWY9mQmpzr5THueZp3Q6YYEDQ0AeIKc83hl5xi3AKCUqPBfpRVmVXaEWQIo5JTLaxmVP3n37gztFok8cRbWyVOZGS3zLnM1QrFNDdp4wzJ49223HSitODcQ+TiOzMf+xUYO6L2gxxwvwZknNweCzXaC56CQE6BMi6m+A9auxyuFsYBXqGw9EDFAOKfIhYyQcV0BVoOBYrQu2WDNpDtJxjJk6qQ5OWnd2hIcYA5ds0nPIvwFw5hZvNcLogtV2Dt1dpycWPbIf/rl+hTySosQLqJljqprhYCgwK82GrvEz2QDbFdHh/iHbUg=
  - secure: bzoKqu1h51zXB3c2tRmN78dF0MZU0LgKY8GmPDza4G+yGgGQZX3DvNk6weuNzv4z9yISx9HIJLV0AzmhYsW1maj8AM97uceLX4HTKj5wt2PPVO5bZBD0alV42dMoQ/GakK6sUmT8doo40BfmdrXHYRbmeontUjdJE5abgPNMmqz1qxMA5CffByXcDwHG0kla/rElbpxKcwFWYgFSlQAecxWatrD9iBSIOWhp5zcj6kjazvRhqiWIItKjiPd4+MHwzf7OU9pBiiXTV5BgFE7m6/4q3FUtyTGohTUn0cgFNMLcpMNwuWFW6AdB/+j3HZT/nOBW+WkY00tBrx6rarmX241go8dc9pdt0A14a/3ECusbJZU2QMXsJ2RKlJTyRjEUBflQbMCSZXDtH1tyvjWRt+w4iw4ix+aJNh1Y+rzlolJ6LNUk0sb0FJ7KiZFfaS2H6F0/Wbgfcnf1acWvyoZ+kdqRleBfDRxEg6s7IgYBht923pueePP813FzLj3/gMqvMZX+jdc83uMRivjHuB/etQykRHEuOlPG8lcaHM9mF8ZW2eD/ZKsbANOUGeNStbWfhdmb7DwY5Vi01KF1oHpwiHTPQCOf23MjuwOtxqJRxDmfwGhqpkL8LjW5IcRtO4or1FgZ/xBuSstjlz63D2e58ohvV8k0ENt3SBTIOfxk0/Q=
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
addons:
  sonarcloud:
    organization: rageshk-github
    token:
      secure: ba6d7d1ad9a369f9f59e4ef1ae06f59dfa24ea35
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export IMAGE_NAME=rageshkh/healthcheeck-img
- docker build $IMAGE_NAME .
- docker push $IMAGE_NAME
